// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuuOG0MMKEQG0gWY9QGtXDBBxwuP-rT-0',
    appId: '1:422250152840:web:78bc8f4afb64bfbeb7703d',
    messagingSenderId: '422250152840',
    projectId: 'newsapplicatino',
    authDomain: 'newsapplicatino.firebaseapp.com',
    storageBucket: 'newsapplicatino.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaBiI21fLBo6aDPG4lttDJivzDzHstSZg',
    appId: '1:422250152840:android:74fdd46363b2327db7703d',
    messagingSenderId: '422250152840',
    projectId: 'newsapplicatino',
    storageBucket: 'newsapplicatino.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjpI7EaS_2TmJyDxd5ubQqBvSw68JFfZA',
    appId: '1:422250152840:ios:894729ae252f22a3b7703d',
    messagingSenderId: '422250152840',
    projectId: 'newsapplicatino',
    storageBucket: 'newsapplicatino.appspot.com',
    iosBundleId: 'com.example.newsapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjpI7EaS_2TmJyDxd5ubQqBvSw68JFfZA',
    appId: '1:422250152840:ios:894729ae252f22a3b7703d',
    messagingSenderId: '422250152840',
    projectId: 'newsapplicatino',
    storageBucket: 'newsapplicatino.appspot.com',
    iosBundleId: 'com.example.newsapplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuuOG0MMKEQG0gWY9QGtXDBBxwuP-rT-0',
    appId: '1:422250152840:web:f3dba9c55d67dea8b7703d',
    messagingSenderId: '422250152840',
    projectId: 'newsapplicatino',
    authDomain: 'newsapplicatino.firebaseapp.com',
    storageBucket: 'newsapplicatino.appspot.com',
  );
}
